[package]
name = "entity_relationship_drawer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.1"
egui = "0.26.1"
egui_plot = "0.26.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
