[package]
name = "entity_relationship_drawer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.14.3"
eframe = "0.26.1"
egui = "0.26.1"
image = "0.24.8"
native-dialog = "0.7.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
